
services:

  postgres:
    image: postgres:17-alpine
    container_name: postgres_app
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: school_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
        reservations:
          cpus: "0.5"
          memory: "256M"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d school_db" ]
      interval: 10s
      retries: 3
      start_period: 10s


volumes:
  postgres_data: